CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node 1 pretraining.py \
    --model_type auto \
    --model_name_or_path  /media/zhangzr/4TB/hf_models/Llama-3.2-1B \
    --train_file_dir ./data/CPT \
    --validation_file_dir ./data/CPT \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --use_peft False \
    --seed 42 \
    --max_train_samples -1 \
    --max_eval_samples 10 \
    --num_train_epochs 1 \
    --lr_scheduler_type cosine \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 100 \
    --eval_steps 100 \
    --evaluation_strategy steps \
    --save_steps 10000 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 10 \
    --block_size 512 \
    --group_by_length False \
    --output_dir outputs-pt \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 32 \
    --lora_alpha 64 \
    --lora_dropout 0.05 \
    --torch_dtype bfloat16 \
    --bf16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --cache_dir ./cache
